### ISSUE TITLE
Improvement suggestion : SSTP as failback

### ISSUE THREAD

**Issue by Supaxor** [ld0614/DPC#2]
Hi, I haven't been able to create a pull request on github, but I would suggest adding a few features:
-the ability to configure SSTP as failback user VPN
-the ability to use or not the logon username and password to connect to the VPN with EAP-MSCHAPv2 instead of a user certificate
-Whether or not to automatically connect to the SSTP VPN at logon.

This would be great in addition to a device tunnel to allow a user to manually connect to the VPN via SSTP if IKEv2 is blocked by a firewall. 

Thanks for the great work guys!

**Comment by ld0614** [comment]
Hi @Supaxor 

Thanks for the suggestions, to address each point:
-the ability to configure SSTP as failback user VPN

You can already do this using the 'VPN Protocol' option within the advanced settings of the user profile

![image](https://github.com/user-attachments/assets/f40d3da0-8ff0-4ee4-8c9e-9e2d095ddb49)

-the ability to use or not the logon username and password to connect to the VPN with EAP-MSCHAPv2 instead of a user certificate

MSCHAPv2 is considered insecure by Microsoft [ref](https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/considerations-known-issues#wi-fi-and-vpn-considerations) and is generally being deprecated. DPC has always had an opinionated approach to security and we don't generally enable options which would be widely considered to be insecure. 

-Whether or not to automatically connect to the SSTP VPN at logon.

If you'd like to disable the VPN from automatically starting when a user logs in that option is under the user profile advanced settings under the option 'Disable Automatic Start'
![image](https://github.com/user-attachments/assets/8a9b5571-83ec-4833-8491-c9538def702a)

**Comment by Supaxor** [comment]
Everything is perfect, I just didn't think that MSCHAPv2 was insecure with EAP protocol.
Thanks for your time and really quick response!
